config/routes.rb
Rails.application.routes.draw do
  get 'manage_expendables', to: 'manage_expendables#list', as: :manage_expendables

  get 'manage_expendables/:house_id', to: 'manage_expendables#category', as: :manage_expendables_category
  get 'manage_expendables/:house_id/:category_id', to: 'manage_expendables#category_w', as: :manage_expendables_category_w

  get 'manage_expendables_new/:house_id', to: 'manage_expendables#new', as: :manage_expendables_new
  get 'manage_expendables_post/:house_id', to: 'manage_expendables#post', as: :manage_expendables_post

  get 'manage_expendables/edit'

  get 'houses', to: 'houses#index', as: :houses

  get 'houses/list'

  get 'houses/new'

  get 'houses/edit'


  # 管理系
  # get 'expendables', to: 'expendables#index', as: :expendables
  # get 'expendables/:id', to: 'expendables#show', as: :expendables_edit
  post 'expendables/:id', to: 'expendables#update', as: :update_expendables
  post 'expendables', to: 'expendables#create', as: :create_expendables
  resources :expendables

  # get 'expendables/list'

  # get 'expendables/new'


  get 'users', to: 'users#index', as: :users
  
  # devise_for :users
  root 'home#index'
  get 'home/index'


  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    get 'users/:id/edit' => 'users/registrations#edit', as: :edit_other_user_registration
    match 'users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/expendable.rb
class Expendable < ApplicationRecord
  belongs_to :category

end

app/controllers/expendables_controller.rb
class ExpendablesController < ApplicationController
  def index
    @expendables = Expendable.all.order(:id)
  end


  # 
  # 
  # [GET] /expendables/:id
  # 
  def show
    @expendable = Expendable.find(params[:id])

  end

  def list
  end

  def new
    @expendable = Expendable.new
    @categories = Category.all

  end


  # 
  # 
  # [GET] /expendables/:id/edit
  # 
  def edit
    @expendable = Expendable.find(params[:id])

  end

  # 
  # 
  # [POST] /expendables
  # 
  def create
    expendable = Expendable.create(expendable_params)
    if expendable.present?
      redirect_to '/expendables/' + expendable.id.to_s

    else
      render 'edit'

    end

  end

  # 
  # 
  # [POST] /expendables
  # 
  def update
    expendable = Expendable.find(expendable_params[:id])
    
    if expendable.update_attributes(expendable_params)
      redirect_to '/expendables/' + expendable.id.to_s

    else
      render 'edit'
    end

  end

  private
  def expendable_params
    params.require(:expendable).permit(:id, :category_id, :display_number, :expendable_type,
                                  :name, :img, :url, :price, :requier_number)
  end
end

app/helpers/expendables_helper.rb
module ExpendablesHelper
end

app/views/expendables/edit.html.slim
.container
  nav.text-left.mb-3
    a.btn.btn-primary href=expendable_path 戻る
    
  - if @expendable.present?
    = form_for(@expendable, url: update_expendables_path(@expendable.id), method: :patch,  html: {id: '', class: ''}) do |f|
      = f.hidden_field :id
      .form-group
        = f.label :display_number
        = f.text_field :display_number, class: 'form-control'
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :img
        = f.text_field :img, class: 'form-control'
      .form-group
        = f.label :requier_number
        = f.text_field :requier_number, class: 'form-control'
      .form-group
        = f.label :url
        = f.text_field :url, class: 'form-control'
      .form-group.text-center
        = f.submit '更新', class: 'btn btn-lg btn-primary'


  

app/views/expendables/index.html.slim
.container
  nav.navbar.mb-3
    a.btn.btn-primary href=root_path ホーム
    a.btn.btn-success href=new_expendable_path 新規
    
  table.table
    thead
      tr
        th ID
        th カテゴリ
        th 名前
        th 画像
        th
    - @expendables.each do |expendable|
      tr
        td #{expendable.id}
        td #{expendable.category.name}
        td #{expendable.name}
        td
          img.img.img-thumbnail src="#{expendable.img}" alt="#{expendable.name}"/
        td
          a.btn.btn-primary href=expendable_path(expendable.id) 詳細

app/views/expendables/list.html.slim
h1 Expendables#list
p Find me in app/views/expendables/list.html.slim

app/views/expendables/new.html.slim
.container
  nav.text-left.mb-3
    a.btn.btn-primary href=expendables_path 戻る

  = form_for(@expendable, url: create_expendables_path, method: :post,  html: {id: '', class: ''}) do |f|
    = f.hidden_field :id

    .form-group
      = f.label :category_id
      = f.select :category_id, @categories.map { |i| [i.name, i.id] }, {}, class: 'custom-select'

    .form-group
      = f.label :display_number
      = f.text_field :display_number, class: 'form-control'

    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control', required: true

    .form-group
      = f.label :img
      = f.text_field :img, class: 'form-control'

    .form-group
      = f.label :requier_number
      = f.text_field :requier_number, class: 'form-control'

    .form-group
      = f.label :url
      = f.text_field :url, class: 'form-control'
   
    .form-group.text-center
      = f.submit '登録', class: 'btn btn-lg btn-primary'


  

app/views/expendables/show.html.slim
.container
  nav.navbar.mb-3
    a.btn.btn-primary href=expendables_path 一覧
    a.btn.btn-primary href=edit_expendable_path(@expendable.id) 編集

  table.table
    tr
      th ID
      td #{@expendable.id}
    tr
      th カテゴリ
      td #{@expendable.category.name}
    tr
      th 表示順
      td #{@expendable.display_number}
    tr
      th 名前
      td #{@expendable.name}
    tr
      th 画像
      td 
        img.img.img-thumbnail src="#{@expendable.img}" alt="#{@expendable.name}"
    tr
      th 商品URL
      td
        a href=@expendable.url 商品詳細
    tr
      th 必要数
      td #{@expendable.requier_number}
      
  

  