config/routes.rb
Rails.application.routes.draw do
  get 'manage_expendables', to: 'manage_expendables#list', as: :manage_expendables

  get 'manage_expendables/:house_id', to: 'manage_expendables#category', as: :manage_expendables_category
  get 'manage_expendables/:house_id/:category_id', to: 'manage_expendables#category_w', as: :manage_expendables_category_w

  get 'manage_expendables_new/:house_id', to: 'manage_expendables#new', as: :manage_expendables_new
  get 'manage_expendables_post/:house_id', to: 'manage_expendables#post', as: :manage_expendables_post

  get 'manage_expendables/edit'

  get 'houses', to: 'houses#index', as: :houses

  get 'houses/list'

  get 'houses/new'

  get 'houses/edit'


  # 管理系
  # get 'expendables', to: 'expendables#index', as: :expendables
  # get 'expendables/:id', to: 'expendables#show', as: :expendables_edit
  post 'expendables/:id', to: 'expendables#update', as: :update_expendables
  post 'expendables', to: 'expendables#create', as: :create_expendables
  resources :expendables

  # get 'expendables/list'

  # get 'expendables/new'


  get 'users', to: 'users#index', as: :users
  
  # devise_for :users
  root 'home#index'
  get 'home/index'


  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    get 'users/:id/edit' => 'users/registrations#edit', as: :edit_other_user_registration
    match 'users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/manage_expendables_controller.rb
module Api
  class ManageExpendablesController < ApiController
    
    # 
    # 注文履歴一覧
    # 
    # ログイン情報からユーザーIDを取得し、
    # 紐づく注文履歴一覧を取得
    # 
    # [POST] /api/manage_expendables/add
    # 
    def add
      expendableChoice = ExpendableChoice.find_by(house_id: expendable_params[:house_id], expendable_id: expendable_params[:expendable_id], status: ExpendableChoice.statuses[:picking])
      if expendableChoice.present?
        expendableChoice.amount += 1
        expendableChoice.save!
        
      else
        expendableChoice = ExpendableChoice.new(expendable_params)
        expendableChoice.status = ExpendableChoice.statuses[:picking]
        expendableChoice.amount = 1
        expendableChoice.save!

      end 

      

      render json: '', status: 204
    end

    # 
    # 足す
    # 
    # [PUT] /api/manage_expendables/plus
    # 
    def plus
      expendableChoice = ExpendableChoice.find(expendable_choice_params[:id])
      expendableChoice.amount += 1
      expendableChoice.save!

      render json: '', status: 204
    end

    # 
    # 引く
    # 
    # [PUT] /api/manage_expendables/minus
    # 
    def minus
      expendableChoice = ExpendableChoice.find(expendable_choice_params[:id])
      expendableChoice.amount -= 1
      expendableChoice.save!

      render json: '', status: 204
    end

    private
    def expendable_params
      params.require(:expendable).permit(:house_id, :expendable_id)
    end

    def expendable_choice_params
      params.require(:expendable_choice).permit(:id)
    end

  end
end

app/controllers/manage_expendables_controller.rb
class ManageExpendablesController < ApplicationController
  before_action :authenticate_user!

  def list
    @houses = House.all
  end

  # 
  # 
  # [GET] /manage_expendables/:house_id
  # 
  def category
    @house = House.find(params[:house_id])
    @house_expenbales = HouseExpendable.where(house_id: @house.id)

    @categories = Category.all
    @expendables = Expendable.where(category_id: 1)
    @category_id = 1

  end

  # 
  # 
  # [GET] /manage_expendables/:house_id/:category_id
  # 
  def category_w
    @house = House.find(params[:house_id])
    @categories = Category.all
    @expendables = Expendable.where(category_id: params[:category_id].to_i)
    @category_id = params[:category_id].to_i

    render "manage_expendables/category"
  end

  def new
    @house = House.find(params[:house_id])
    @expendable_choices = ExpendableChoice.where(house_id: @house.id, status: ExpendableChoice.statuses[:picking])

    
  end
  
  def post
    house = House.find(params[:house_id])
    expendable_choices = ExpendableChoice.where(house_id: house.id, status: ExpendableChoice.statuses[:picking])
    zero_amount_expendable_choices = expendable_choices.where(amount: 0)
    zero_amount_expendable_choices.destroy_all

    ManageExpendableMailer.send_choice(user: current_user, house: house, expendable_choices: expendable_choices).deliver
    expendable_choices.update_all(status: ExpendableChoice.statuses[:ordered])

    redirect_to root_path
  end

  def edit
  end

  def add
  end

  
end

app/helpers/manage_expendables_helper.rb
module ManageExpendablesHelper
end

app/views/manage_expendables/category.html.slim
.container-fluid
  .row
    .col-3
      nav.mb-3
        ul.nav.nav-tabs.d-block
          - if @categories.present?
            - @categories.each do |category|
              li.d-block.nav-item.mb-2
                - if @category_id == category.id
                  a.btn.btn-lg.category-menu-btn.text-truncate.nav-link.active.bg-info.text-light href=manage_expendables_category_w_path(@house.id, category.id) #{category.name}
                - else
                  a.btn.btn-lg.category-menu-btn.text-truncate.nav-link.active href=manage_expendables_category_w_path(@house.id, category.id) #{category.name}
    .col-9
      .row.mb-3
        .col.text-left
          a.btn.btn-secondary href="/manage_expendables"
            = fa_icon('chevron-left', class: 'fa-fw')
            | 戻る
        .col.text-center.category-label-house
          strong #{@house.name}
          label の消耗品管理
        .col.text-right
          a.btn.btn-secondary href="/manage_expendables_new/#{@house.id}"
            | 選択リスト
            = fa_icon('chevron-right', class: 'fa-fw')

      - if @expendables.present?
        .row
          - @expendables.each do |expendable|
            .col-4.text-center
              .card.p-2.mb-2 onclick="addToOrder(#{@house.id}, #{expendable.id}, '#{expendable.name}')"
                label #{expendable.name}
                img.img.img-thumbnail.d-block src="#{expendable.img}" alt="#{expendable.name}"/

      - else
        dev 消耗品はありません


javascript:
  
  function addToOrder(house_id, expendable_id, expendable_name) {
    console.log('aaa');
    console.log(expendable_id);

    $.ajax({
      type: 'POST',
      url: '/api/manage_expendables/add',
      dataType: 'json',
      data: { expendable: {
        'house_id': house_id,
        'expendable_id': expendable_id
        }
      },
      success: function (data) {
        console.log(data);
        console.log('ok')
        notifySuccess('リストに追加', expendable_name)

      },
      error: function () {
        console.log('ng')
      }
    });
  }

app/views/manage_expendables/edit.html.slim
h1 ManageExpendables#edit
p Find me in app/views/manage_expendables/edit.html.slim

app/views/manage_expendables/list.html.slim
.container
  .row
    - @houses.each do |house|
      .col-md-4.col-content
        a href=manage_expendables_category_path(house.id)
          .col-item.p-3
            label #{house.name}

            img.img.img-thumbnail.d-block src="#{house.img}" alt="#{house.name}"/

app/views/manage_expendables/new.html.slim
.container
  .row.mb-3
    .col.text-left
      a.btn.btn-secondary href="/manage_expendables/#{@house.id}"
        = fa_icon('chevron-left', class: 'fa-fw')
        | 戻る
    .col.text-center.category-label-house
      strong #{@house.name}
      label の消耗品管理
    .col.text-right
      - if @expendable_choices.present?
        a.btn.btn-secondary href="/manage_expendables_post/#{@house.id}"
          | メール送信
          = fa_icon('chevron-right', class: 'fa-fw')
  table.table
    tr
      th No
      th カテゴリ
      th 名前
      th 数
      th

    - if @expendable_choices.present?
      - @expendable_choices.each_with_index do |expendable, index|
        tr
          td.align-middle.td-min.text-center #{index + 1}
          td.align-middle #{expendable.expendable.category.name}
          td.align-middle #{expendable.expendable.name}
          td.align-middle.td-min.text-center id="choice-#{expendable.id}" #{expendable.amount}
          td.align-middle.td-min
            span onclick="plus(#{expendable.id})"
              = fa_icon('plus-square', class: 'fa-3x text-secondary')
            span onclick="minus(#{expendable.id}, #{expendable.expendable.id})"
              = fa_icon('minus-square', class: 'fa-3x text-secondary ml-3')
            
javascript:
  function plus(choiceId, expendableId) {
    
    $.ajax({
      type: 'PUT',
      url: '/api/manage_expendables/plus',
      dataType: 'json',
      data: { expendable_choice: {
        'id': choiceId
        }
      },
      success: function (data) {
        choiceElm = document.getElementById('choice-' + choiceId);
        choiceElm.innerText = parseInt(choiceElm.innerText) + 1;

      },
      error: function () {
        console.log('ng')

      }
    });
  }


  function minus(choiceId, expendableId) {

    $.ajax({
      type: 'PUT',
      url: '/api/manage_expendables/minus',
      dataType: 'json',
      data: { expendable_choice: {
        'id': choiceId
        }
      },
      success: function (data) {
        choiceElm = document.getElementById('choice-' + choiceId);
        choiceElm.innerText = parseInt(choiceElm.innerText) - 1;

      },
      error: function () {
        console.log('ng')

      }
    });
  }